export const enum FieldTypes {
    text = 'text',
    number = 'number',
    tree = 'tree',
    textarea = 'textarea',
    password = 'password',
    picker = 'picker',
    pickers = 'pickers',
    pickerTags = 'pickerTags',
    search = 'search',
    date = 'date',
    time = 'time',
    datetime = 'datetime',
    year = 'year',
    radio = 'radio',
    checkers = 'checkers',
    switch = 'switch',
    img = 'img',
    video = 'video',
    editor = 'editor',
    group = 'group',
}
